name: Flutter CI

on: push

jobs:
  build-and-release-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          flutter-version: '3.24.3'
      - name: Install project dependencies
        run: flutter pub get
      - name: Enable Windows build
        run: flutter config --enable-windows-desktop
      - name: Build Windows executable
        run: flutter build windows --release
      - name: Upload Windows executable
        uses: actions/upload-artifact@v3
        with:
          name: MyFlutterApp
          path: build/windows/runner/Release/MyFlutterApp.exe  # Replace with your actual executable name
